name: MineX
version: '${version}'
main: dev.kacperm.mineX.MineX
api-version: '1.21'
commands:
  prompt1:
  prompt2:
  prompt3:
  prompt4:
  prompt5:
  promptblue:
  promptyellow:
  promptorange:
  promptwronghouse1:
  promptwronghouse2: